name: Build APK

on:
  push:
    branches:
      - main  # Change to your branch if needed

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Clean the project
      - name: Clean Flutter project
        run: flutter clean

      # Build APK
      - name: Build APK
        run: flutter build apk --release

      # Upload APK as an artifact (updated to latest)
      - name: Upload APK
        uses: actions/upload-artifact@latest
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
